### ISSUE TITLE
openai.error.AuthenticationError

### ISSUE THREAD

**Issue by oussevo** [feranick/OpenAI_GTP3#1]
Hello, the code dosen't work and everytime i have an error : "openai.error.AuthenticationError" knowing that i got everything as you said for the API key and the type of the file.

Thank you

**Comment by feranick** [comment]
Works fine with my multiple setups (Linux, MacOS). Make sure you have registered with OpenAI to get your key to for the line:

```export OPENAI_API_KEY="YOUR_OPENAI_API_KEY"```

The code won't work without such key.
